language: java

jdk:
  - oraclejdk7

script:
  - ./travis.sh

install: true

sudo: false

cache:
  directories:
    - $HOME/.m2/repository
    # for analysis
    - $HOME/.sonar

notifications:
  email: false
